Areas/Admin/Controllers/BrandController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shopping_mvc8.Models;
using Shopping_mvc8.Repository;

namespace Shopping_mvc8.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BrandController : Controller
    {
        private readonly DataContext _dataContext;
        public BrandController(DataContext dataContext)
        {
            _dataContext = dataContext;
        }
        public async Task<IActionResult> Index(int pg = 1)
        {
            List<BrandModel> brand = _dataContext.Brands.ToList();
            const int pageSize = 10;
            if (pg < 1)
            {
                pg = 1;
            }
            int recsCount = brand.Count();// dem so item 
            var pager = new Paginate(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = brand.Skip(recSkip).Take(pager.PageSize).ToList();
            ViewBag.Pager = pager;
            return View(data);
        }

        public async Task<IActionResult> Delete(int Id)
        {
            BrandModel brand = await _dataContext.Brands.FindAsync(Id);
            _dataContext.Brands.Remove(brand);
            await _dataContext.SaveChangesAsync();
            TempData["success"] = "Delete brand success";
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BrandModel brand)
        {
            if (ModelState.IsValid)
            {
                brand.Slug = brand.Name.Replace(" ","-").ToLower();
                var slug = await _dataContext.Brands.FirstOrDefaultAsync(b => b.Slug == brand.Slug);
                if (slug != null)
                {
                    ModelState.AddModelError("", "The database has this brand.");
                    return View(brand);
                }
                _dataContext.Add(brand);
                await _dataContext.SaveChangesAsync();
                TempData["success"] = "Add brand success";
                return RedirectToAction("Index");
            }
            else
            {
                List<string> errors = new List<string>();
                foreach( var value in ModelState.Values)
                {
                    foreach( var error in value.Errors)
                    {
                        errors.Add(error.ErrorMessage);
                    }
                }
                string errorMesage = string.Join("\n", errors);
                return BadRequest(errorMesage);
            }
        }
        public async Task<IActionResult> Edit(int Id)
        {
            BrandModel brand = await _dataContext.Brands.FindAsync(Id);
            return View(brand);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BrandModel brand)
        {
            if(ModelState.IsValid)
            {
                brand.Slug = brand.Name.Replace(" ","-").ToLower();
                _dataContext.Update(brand);
                await _dataContext.SaveChangesAsync();
                TempData["success"] = "Edit category success";
                return RedirectToAction("Index");
            }
            else
            {
                List<string> errors = new List<string>();
                foreach( var value in ModelState.Values )
                {
                    foreach( var error in value.Errors)
                    {
                        errors.Add(error.ErrorMessage);
                    }
                }
                string errorMessage = string.Join("\n",errors);
                return BadRequest(errorMessage);
            }
        }
    }
}

Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shopping_mvc8.Models;
using Shopping_mvc8.Repository;
using System.Collections.Specialized;

namespace Shopping_mvc8.Controllers
{
	public class BrandController : Controller
	{
		private readonly DataContext _dataContext;
		public BrandController(DataContext Context)
		{
			_dataContext = Context;
		}
		public async Task<IActionResult> Index(string Slug = "")
		{
			BrandModel brand = _dataContext.Brands.Where(b => b.Slug == Slug).FirstOrDefault();
			if (brand == null) return RedirectToAction("Index");
			return View( await _dataContext.Products.Where(p => p.BrandId == brand.Id)
				.OrderByDescending(p => p.Id).ToListAsync());
		}
	}
}

Areas/Admin/Views/Brand/Create.cshtml
@model BrandModel
@{
    ViewData["title"] = "Create Brand";
}
<h2>Create Brand</h2>
<div class="col-md-9">
    <form asp-action="Create" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class ="form-group">
            <label>Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger" />
        </div>
        <div class ="form-group">
            <label>Description</label>
            <textarea asp-for ="Description" class="form-control"></textarea>
            <span asp-validation-for="Description" class="text-danger" />
        </div>
        <div class="form-group">
            <label>Status</label>
            <select asp-for="Status" class="form-control">
                <option value="1">Display</option>
                <option value="0">Hidden</option>
            </select>
            <span asp-validation-for="Status" class="text-danger"/>
        </div>
        <div class="form-group">
            <button class="btn btn-primary">Create</button>
        </div>
    </form>
    <a asp-action="Index" asp-controller="Brand">Back</a>
</div>
@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Areas/Admin/Views/Brand/Edit.cshtml
@model BrandModel
@{
    ViewData["title"] = "Edit Brand";
}
<h2>Edit Brand</h2>
<div class="col-md-9">
    <form asp-action="Edit" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label>Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger" />
        </div>
        <div class="form-group">
            <label>Description</label>
            <textarea asp-for="Description" class="form-control"></textarea>
            <span asp-validation-for="Description" class="text-danger" />
        </div>
        <div class="form-group">
            <label>Status</label>
            <select asp-for="Status" class="form-control">
                <option value="1">Display</option>
                <option value="0">Hidden</option>
            </select>
            <span asp-validation-for="Status" class="text-danger" />
        </div>
        <div class="form-group">
            <button class="btn btn-primary">Update</button>
        </div>
    </form>
    <a asp-action="Index" asp-controller="Brand">Back</a>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Areas/Admin/Views/Brand/Index.cshtml
@model IEnumerable<BrandModel>
@{
    ViewData["title"] = "Brand Listed";
    Paginate pager = new Paginate();
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
    }
}
<h3>List Brand</h3>
<a class="btn btn-warning btn-sm" asp-action="Create" asp-controller="Brand">Add Brand</a>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Brand Name</th>
            <th scope="col">Brand Desription</th>
            <th scope="col">Brand Slug</th>
            <th scope="col">Brand Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@item.Id</th>
                <td>@item.Name</td>
                <td>@Html.Raw(item.Description)</td>
                <td>@item.Slug</td>
                <td>
                    @if (item.Status == 1)
                    {
                        <span class="text text-success">Display</span>
                    }
                    else
                    {
                        <span class="text text-danger">Hidden</span>
                    }
                </td>
                <td>
                    <a class="btn btn-warning btn-sm" asp-action="Edit" asp-controller="Brand" asp-route-Id="@item.Id">Edit</a>
                    <a class="btn btn-danger btn-sm confirmDeletion" asp-action="Delete" asp-controller="Brand" asp-route-Id="@item.Id">Delete</a>
                </td>
            </tr>
        }

    </tbody>
</table>

<partial name="_Paging" model="@pager" />